In [ ]:
# introduction to python 
# pandas is an open source library which is used for handle data manuplatior

In [1]:
import pandas as pd

In [ ]:
#  data structure with pandas 
# 1 series => it is one dimensional array and it returns only values not the column name  

# 2 data frame => it is multi dimension array and it returns values with column name

In [4]:
# series 

a = pd.Series([1,34,78,90])
a

0     1
1    34
2    78
3    90
dtype: int64

In [6]:
type(a)

pandas.Series

In [7]:
# data frame

In [8]:
a = {
    "emp_id":[1,2,3,4,5],
    "name":["aditya","vipul","govind","diwanshi","khemish"],
    "department":["IT","sales","it","it","sales"],
    "working_hours":[8,9,9,8,9]
}

In [9]:
type(a)

dict

In [12]:
df = pd.DataFrame(a)
df

   emp_id      name department  working_hours
0       1    aditya         IT              8
1       2     vipul      sales              9
2       3    govind         it              9
3       4  diwanshi         it              8
4       5   khemish      sales              9

In [13]:
df.to_csv("emp_data.csv")

In [15]:
df.to_csv("emp_data_without_index.csv",index = False)

In [ ]:
# import this df using pandas 
#  use copy path in  read_csv("your data set path")

In [19]:
df1 = pd.read_csv("your data set path")
df1

   Unnamed: 0  emp_id      name department  working_hours
0           0       1    aditya         IT              8
1           1       2     vipul      sales              9
2           2       3    govind         it              9
3           3       4  diwanshi         it              8
4           4       5   khemish      sales              9

In [20]:
df2 = pd.read_csv("C:/Users/acer'mall/Desktop/data science/pandas/emp_data_without_index.csv")
df2

   emp_id      name department  working_hours
0       1    aditya         IT              8
1       2     vipul      sales              9
2       3    govind         it              9
3       4  diwanshi         it              8
4       5   khemish      sales              9